### ISSUE TITLE
Add support for pending breakpoints using shortname

### ISSUE THREAD

**Issue by chipsenkbeil** [ensime/scala-debugger#231]
As I discovered when running Ensime's integration tests, they are setting pending breakpoints before the VM is started. This would be okay except for the fact that I added logic to convert short names (file.scala) to paths (org/potato/file.scala), which requires an active VM to look up the information (dummy VMs can't do anything).

The solution is to add ShortBreakpointRequestInfo that has a field for the short name and, when being processed, will perform the task of looking up the source path to use in the real breakpoint.

This means adding methods to the low level breakpoint manager, pending breakpoint support, and pure breakpoint profile to specify a breakpoint using the short name.

[EDIT]
Given the flexibility of the pending action manager, I don't need to create an entire new data structure. Instead, the pending action manager can store the information and swap out the filename with the full source path during the action.

With the scoped variables available, it is just a matter of wrapping the file name with a converter that will be performed every time we try to set the breakpoint.
```scala
def createBreakpoint() = {
  super.createBreakpointWithRequestId(
    requestId,
    convertToSourcePath(shortFileName),
    lineNumber,
    extraArguments
  )
}

pendingActionManager.addPendingActionWithId(
  requestId,
  BreakpointRequestInfo(
    requestId,
    isPending = true,
    shortFileName,
    lineNumber,
    extraArguments
  ),
  () => createBreakpoint().get
)
```

**Comment by chipsenkbeil** [comment]
Making it even easier by providing a JDI request extra argument that indicates that the file name is short. Integration test is failing, so need to figure out why the scala files are not showing up in the class manager.

**Comment by chipsenkbeil** [comment]
Based on discussion with @fommil, this is invalid. If the Scala source files don't necessarily reflect to the generated Java source paths. I've added a test to reflect this. To handle this scenario, need to grab the proper paths from Ensime instead of using the debugger API.

**Comment by fommil** [comment]
we don't even support all possibilities in ENSIME, but one day somebody might come up with an algorithm that handles more cases. We pretty much only support the case where the file is where you'd expect it, or in a parent directory, but it's all cached (in the DB) so this lookup is super fast.
