### ISSUE TITLE
profile the test compile

### ISSUE THREAD

**Issue by fommil** [ensime/scala-debugger#306]
@rorygraves the tests take forever to compile. I'm almost certain a CPU profiling session would be highly revealing... possibly a macro somewhere.

**Comment by chipsenkbeil** [comment]
Also adding @dickwall, since he had taken a look earlier.

**Comment by fommil** [comment]
https://github.com/paulbutcher/ScalaMock/issues/169

**Comment by fommil** [comment]
after spending the evening on it, I conclude that scalamock is just fundamentally slow.

Like shapeless, it boils down to the question: is this functionality worth the compile hit?

Probably it is at this point, given how many tests you've written. But I think I'd use this as a cautionary tale not to use scalamock because I don't often find myself needing to mock anything - it's rare that one ever needs to manage state in scala, without using actors, which can be trivially mocked.
