### ISSUE TITLE
How to get all variables while breakpoint in loop 

### ISSUE THREAD

**Issue by igreenfield** [ensime/scala-debugger#368]
I have this class:
```scala
object UnderDebug{

  val d = "ffff"
  def main(args: Array[String]): Unit = {
    while (true) {
      val a = 5
      (1 to 10).foreach { index =>
        val f = index * a
        val g = index + a
        val z = f / g

        println(z)

      }
    }
  }
}
```
and I load the debuger:
```scala
object ReplDebuger {

  def main(args: Array[String]): Unit = {
    // Get the executing class name (remove $ from object class name)
    val klass = UnderDebug.getClass
    val className = klass.getName.replaceAllLiterally("$", "")
    // Add our main class to the classpath used to launch the class
    val classpath = JDITools.jvmClassPath
    val jvmOptions = Seq("-classpath", classpath)

    // Checks if the JDI is available in your runtime
    // classloader or by extracting it from tools.jar
    // found in JDK_HOME or JAVA_HOME
    println("JDI is available: " + JDITools.isJdiAvailable())

    // Loads the JDI from tools.jar and attempts to
    // add it to your system classloader
    println("Loaded JDI: " + JDITools.tryLoadJdi())

    val launchingDebugger = LaunchingDebugger(className = className,
      jvmOptions = jvmOptions,
      suspend = true // Wait to start the main class until after connected)
    )
    import org.scaladebugger.api.profiles.scala210.Scala210DebugProfile.Name
    launchingDebugger.start { s => println("Launched and connected to JVM: " + s.uniqueId)
      val pipeline =
        s.withProfile(org.scaladebugger.api.profiles.scala210.Scala210DebugProfile.Name)
          .getOrCreateBreakpointRequestWithData(JDITools.scalaClassStringToFileString(className), 12, CustomPropertyDataRequest("f"))



      pipeline.foreach{e =>
        val path = e._1.location.sourcePath
        val line = e._1.location.lineNumber

        println(s"Reached breakpoint for $path:$line")
        launchingDebugger.stop()
      }

    }
```

I do not get any values of the local variables: `f` and `g`

What I am doing wrong?

**Comment by chipsenkbeil** [comment]
Sometimes the JVM transforms those variables into inline representations. Other times it turns them into methods that are invoked. What this says to me is that they are not avaiable as local variables, but maybe they are exposed in some other form. Have you tried connecting `sdb` to your code above and printing out variable information including the contents of `this` to see if you can find the variables?

The profile abstractions for Scala need some work to get them to be a bit cleaner. 

You can look at [this test](https://github.com/ensime/scala-debugger/blob/f8e69614d71786605b4baa8c62f0968683936d22/scala-debugger-api/src/it/scala/org/scaladebugger/api/profiles/java/info/JavaFrameInfoIntegrationSpec.scala#L95), which debugs [Variables.scala](https://github.com/ensime/scala-debugger/blob/master/scala-debugger-test/src/main/scala/org/scaladebugger/test/info/Variables.scala) to see examples of how data is parsed. It uses the top frame of the thread to get a list of variables. Try doing that in your pipeline to print out the list of variables and see if "f" and "g" are there.

**Comment by igreenfield** [comment]
Thanks
